{
  config,
  pkgs,
  lib,
  inputs,
  user,
  ...
}:

{
  imports = [
    ../common.nix # Genuinely universal settings only (timezone, locale, ssh hardening, nix gc)
    ./hardware-configuration.nix # Generated by nixos-generate-config during install — do not hand-write
    ./zfs.nix
    ./nfs.nix
  ];

  # Deliberately NOT importing hosts/revachol-cluster/revachol-common.nix — that file is a
  # k3s-node role file (firewall disabled, services.nfs.server.enable=false, openiscsi,
  # a kernel pin that's incompatible with ZFS on 25.05+), not a fleet-wide common file.
  # See the migration report, Q1, for the full reasoning.

  networking.hostName = "dolores";
  networking.networkmanager.enable = lib.mkForce false; # server, static config below
  networking.useDHCP = false;
  networking.interfaces.eno1.ipv4.addresses = [
    {
      address = "192.168.1.34"; # matches current DHCP-observed address; move to a real reservation on the router
      prefixLength = 24;
    }
  ];
  networking.defaultGateway = "192.168.1.1";
  networking.nameservers = [ "1.1.1.1" "8.8.8.8" ];

  # exportfs resolves every client hostname in /etc/exports at load time. Cluster's own
  # CoreDNS now serves .home (see gitops-cluster infra/coredns), which means dolores
  # exporting to dubois.home/cuno.home/katsuragi.home would silently fail to register
  # whenever the cluster itself is down — confirmed live: exportfs -ra threw
  # "Failed to resolve dubois.home" etc. while the cluster nodes were powered off during
  # this migration, and only the one export using a raw IP actually loaded. Same class of
  # bootstrap circular-dependency as the CSI controller's SSH target — same fix: pin
  # statically, independent of any DNS resolver.
  networking.hosts = {
    "192.168.1.155" = [ "dubois.home" ];
    "192.168.1.156" = [ "cuno.home" ];
    "192.168.1.157" = [ "katsuragi.home" ];
  };

  # Unlike revachol-common.nix, dolores gets a real firewall — it holds every
  # database in the homelab and NFS is no_root_squash.
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [
    22 # ssh
    111 # rpcbind
    2049 # nfsd
  ];
  networking.firewall.allowedUDPPorts = [
    111
  ];
  # TODO: once this is stable, tighten source ranges to the cluster node IPs only
  # (192.168.1.155/.156/.157) via extraCommands / a proper allowedTCPPortRanges + IP set,
  # rather than opening NFS to the whole LAN.

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  time.timeZone = "Europe/Madrid";
  console.keyMap = "uk"; # matches the rest of the fleet

  # Admin user — matches the revachol-cluster convention (same account, same keys) rather
  # than recreating dolores's old "monederobox" login. Flag if you'd rather keep that name.
  users.users.${user} = {
    isNormalUser = true;
    description = "NAS admin";
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMlMp3gOmuiGEjtG7d/c7CIqQpId49EZoX5Nu1J6Pfuo" # ntb user
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOOVwSQAPzm403xgtVXkniuc3r8v16l9rFl5CBJH8zZs" # cfv@hatsum
    ];
  };

  security.sudo.wheelNeedsPassword = true;

  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    vim
    wget
    git
    htop
    tmux
    smartmontools
    nfs-utils
  ];

  # No agenix here on purpose — dolores decrypts nothing today. The CSI SSH trust only
  # needs revachol-csi-user's PUBLIC key (set in nfs.nix), which isn't a secret. See the
  # migration report, Q5, for why dolores should stay out of the cluster's secrets.nix.

  system.stateVersion = lib.mkForce "25.05"; # fresh install — overrides common.nix's fleet default of 24.11
}
